print("Who wrote Hamlet?")
input()
print("William Shakespeare.")
print()
print("What is the capital of Nunavut?")
input()
print("Iqaluit.")
print()
print("What\'s Python?")
input()
print("It\'s a snake and also the name of a programming language.")
